# Site
name: "Gonzalo's Blog"
title: "Mediumish"
description: "Personal blog with self-hosting guides and tutorials"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  gonzalo:
    name: Gonzalo García Hernantes
    display_name: Gonzalo    
    avatar: 'assets/images/avatar.jpg'
    # gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: gonzalo.garhtes@gmail.com
    web: https://blog.gonzaverse.com
    linkedin: https://www.linkedin.com/in/gonzalogarcia-h/
    description: "I'm Gonzalo, a young DevOps engineer. In my spare time, I like to have some fun with my Raspberry which allows me to learn new things about Linux and microservices."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE, CNAME, README.md, Gemfile, Gemfile.lock]
